name: Create a comment on new created issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'

  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment from API
        run: |
          gh api -X POST -F body='Comment but from API Call' \
          "repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
